#!/usr/bin/env python3
"""
Workspace Migration Step 1: Convert Marin to uv workspace structure.

This script orchestrates the transformation from a single-package repo
to a uv workspace with lib/marin as a member and experiments at root.

Transformations:
1. Update .gitignore to allow lib/
2. Move src/marin → lib/marin/src/ and marin/tools → lib/marin/tools/
3. Create lib/marin/pyproject.toml and update root pyproject.toml
4. Update file paths in workflows, docs, Makefile, mkdocs.yml
5. Update CI/docs configs for workspace (GHA extras, ReadTheDocs)
6. Update uv.lock to reflect workspace structure

Requirements:
- Must be run from marin repo root
- Assumes clean working directory (or at least no conflicts with changes)
"""

import subprocess
import sys
from pathlib import Path


def run_command(cmd, description, check=True):
    """Run a shell command and print output."""
    print(f"\n{'='*60}")
    print(f"{description}")
    print(f"{'='*60}")
    print(f"$ {cmd}\n")

    result = subprocess.run(cmd, shell=True, check=check, capture_output=False)
    if result.returncode != 0 and check:
        print(f"\n❌ Command failed: {cmd}", file=sys.stderr)
        sys.exit(1)
    return result


def check_repo_root():
    """Verify we're in the marin repo root."""
    if not Path('pyproject.toml').exists():
        print("❌ Error: pyproject.toml not found. Run from marin repo root.", file=sys.stderr)
        sys.exit(1)

    if not Path('src/marin').exists():
        print("❌ Error: src/marin not found. Has step-1 already been run?", file=sys.stderr)
        sys.exit(1)

    print("✓ Running from marin repo root")


def main():
    """Execute step-1 transformation."""
    print("""
╔══════════════════════════════════════════════════════════════╗
║  Marin Workspace Migration - Step 1                          ║
║  Converting to uv workspace structure                        ║
╚══════════════════════════════════════════════════════════════╝
""")

    check_repo_root()

    # Step 1: Update .gitignore
    run_command(
        "sed -i '' '/^lib\\/$/d' .gitignore",
        "Step 1: Update .gitignore to allow lib/"
    )

    # Step 2: Move files to lib/marin structure
    # Check if already moved
    if Path("lib/marin/src").exists() and not Path("src").exists():
        print("\n" + "="*60)
        print("Step 2: Move marin code to lib/marin/")
        print("="*60)
        print("  → lib/marin/src already exists, skipping move\n")
    else:
        # Clean up partial migration if needed
        if Path("lib/marin").exists():
            print("\n  → Cleaning up partial lib/marin structure")
            subprocess.run("rm -rf lib/marin", shell=True, check=True)

        run_command(
            """
            mkdir -p lib/marin &&
            git mv src lib/marin/ &&
            git mv marin/tools lib/marin/ &&
            rmdir marin
            """,
            "Step 2: Move marin code to lib/marin/"
        )

    # Step 3: Transform pyproject.toml files
    script_dir = Path(__file__).parent
    run_command(
        f"{script_dir}/transform_pyprojects.py",
        "Step 3: Transform pyproject.toml files"
    )

    # Step 4: Update paths in other files
    run_command(
        f"{script_dir}/update_paths.py",
        "Step 4: Update file paths in workflows, docs, Makefile"
    )

    # Step 5: Update CI/docs configs for workspace
    run_command(
        f"{script_dir}/update_ci_docs.py",
        "Step 5: Update CI/docs configs for workspace structure"
    )

    # Step 6: Update uv.lock to reflect workspace structure
    run_command(
        "uv lock",
        "Step 6: Update uv.lock for workspace structure"
    )

    # Step 7: Commit the changes
    commit_message = """Workspace migration step-1: Convert to uv workspace structure

Convert Marin from single-package to uv workspace:
- Move src/marin → lib/marin/src/, marin/tools → lib/marin/tools/
- Create lib/marin/pyproject.toml (all deps/extras, no tool configs)
- Replace root pyproject.toml (workspace + experiments package)
- Root depends on marin, packages experiments/ (no move needed)
- experiments/ stays at root (imports from marin workspace member)
- data_browser/ stays independent (not a workspace member)
- Tool configs (black, ruff, mypy, pytest) stay at root
- Update all path references in workflows, docs, Makefile, mkdocs.yml
- Add --package marin to uv export in ray_deps.py
- Update CI/docs configs: GHA uses --extra=marin:cpu, ReadTheDocs installs lib/marin
- Update uv.lock to reflect new workspace structure (marin source: lib/marin)

Structure after step-1:
  /
  ├── pyproject.toml          # Workspace root + experiments package
  ├── lib/marin/              # Workspace member (all marin deps/extras)
  ├── experiments/            # Part of root package (imports from marin)
  └── data_browser/           # Independent (unchanged)

Generated by: ./workspace-migration/step1/main.py"""

    # Write commit message to temp file and use git commit -F
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write(commit_message)
        msg_file = f.name

    try:
        run_command(
            f"git add -u && git add lib/ && git commit -F {msg_file}",
            "Step 7: Commit workspace migration"
        )
    finally:
        Path(msg_file).unlink()

    print("""
╔══════════════════════════════════════════════════════════════╗
║  ✓ Step 1 Complete!                                          ║
╚══════════════════════════════════════════════════════════════╝

Structure after step-1:
  /
  ├── pyproject.toml          # Workspace root + experiments package
  ├── lib/marin/              # Workspace member (all marin deps/extras)
  ├── experiments/            # Part of root package (imports from marin)
  └── data_browser/           # Independent (unchanged)

Next steps:
  1. Test: uv sync
  2. Proceed to step-2 (levanter integration) when ready
""")


if __name__ == '__main__':
    main()
